<?php
$persons = isset($_POST['persons']) ? strip_tags($_POST['persons']) : "";
$teamsCount = isset($_POST['teams']) ? strip_tags($_POST['teams']) : 0;

// define our people and teams as simple arrays
// for ($i = 1; $i < 71; $i++) {
//     $people[] = "person" . $i;
// }
$people = explode("\n", str_replace("\r", "", $persons));;

for ($i = 1; $i < ($teamsCount + 1); $i++) {
    $teams[] = "tim " . $i;
}

shuffle($people);

// what team are we adding to?
$teamidx = 0;

// loop through people, add them to a team
// when you run out of teams, shuffle the team
// order for giggles and start back at the first
// team
for ($i = 0; $i < count($people); $i++) {
    $teammembers[$teams[$teamidx]][] = $people[$i];
    $teamidx++;
    if ($teamidx == count($teams)) {
        $teamidx = 0;
        shuffle($teams);
    }
}

// echo json_encode($teammembers);
for ($i = 1; $i <= count($teammembers); $i++) {
    echo "tim " . $i . "\r\n";
    for ($j = 0; $j < count($teammembers["tim " . $i]); $j++) {
        echo "-" . $teammembers["tim " . $i][$j] . "\r\n";
    }
    echo "\r\n";
}
echo "Generated by teams generator";
